var A2=(0,z.forwardRef)(({handleSubmit:a,restoreReviewComments:b,cancelInvocation:c,inputClassName:e,mentionsConfig:f,comments:g,inputPlaceholder:h,initialContent:k,isRunning:l,hasPendingComments:m,isConvoLoading:n,modelSelector:p,optOutButton:q,optOutBanner:t,agentSelector:u,permissionsSelector:v,showBottomToolbar:w,currentModelConfig:y,sideQuestionControl:A,dropdownPlacement:B="top-start",allowVideo:C,resolveWorkspaceUrlPreview:D,onDriveLinkResolveError:F,captureScreenRecording:E,capturedScreenshotEvent:I,
getSlashCommandItems:G,getMcpPrompt:J,contextMenuPopupFn:K,agentScripts:L,cascadeId:M,inExistingConversation:P,conversationAgentScript:N,messageHistoryConfig:Q,hasQuotaOrCredits:O,resourceManagementProps:S,selectedEnvironment:W,setSelectedEnvironment:Z,environmentSelectorCompact:aa,isCreatingEnvironment:ca,isGitRepo:ba,isCitcWorkspace:ha,isPendingNewWorkspace:na,isPseudoProjectSelected:oa,topToolbarContent:ua,disableAutoFocus:la,battleMode:da,autonomousModeConfig:qa,isSignedIn:ea,floatingBanner:pa,
prefetchSlashCommands:fa,onPromptTextChange:ya,collapseToolbarWhenInactive:xa,aboveContent:ja},wa)=>{var va=pk(),sa=va.get("supportsWorkflows"),Ca=va.get("supportsImageDragDrop"),Fa=va.get("isRemoteControl")??!1,Ia=rH(),{logEvent:ma}=Fy(),{deleteAgentMessage:Ma}=Bx(),[Ba,Ja]=(0,z.useState)([]),La=h?h:"Ask anything, @ to mention"+(sa?", / for actions":""),[pb,lb]=(0,z.useState)(null),[Xa,Gb]=(0,z.useState)(!1),[Va,Ra]=(0,z.useState)(null),{isUploading:db,getMedia:Aa,forgetTrackedUploads:Oa}=g4a(Ba,
lb);(0,z.useEffect)(()=>{I?.(xd=>{Ja(Cd=>[...Cd,xd])})},[I]);var Ta=(0,z.useCallback)(xd=>{Ja(Cd=>[...Cd,xd])},[]),{startRecording:ab,stopRecording:Ua,cancelRecording:Ka,isRecording:Cb,error:oc,hasMicrophone:xc}=S3a(Ta),Pb=(0,z.useRef)(null),Na=z.useMemo(()=>BIb(ma),[ma]),{startStreaming:kb,stopStreaming:Jb,stopAndFinalize:gb,cancelStreaming:yb,isStreaming:qc,isFinalizing:dc,isSubmittingAudio:yc,error:ud,hasMicrophone:Vd,isAudioStreamingAvailable:Cf}=qH({editorRef:Pb,cascadeId:M,logEvent:Na}),$e=
(0,z.useCallback)(()=>Promise.resolve(),[]),ed=(0,z.useMemo)(()=>Cf?{startRecording:kb,stopRecording:Jb,stopAndFinalize:gb,cancelRecording:yb,isRecording:qc,isFinalizing:dc,isSubmittingAudio:yc,error:ud,hasMicrophone:Vd}:{startRecording:ab,stopRecording:Ua,stopAndFinalize:$e,cancelRecording:Ka,isRecording:Cb,isFinalizing:!1,isSubmittingAudio:!1,error:oc,hasMicrophone:xc},[Cf,kb,Jb,gb,yb,qc,dc,yc,ud,Vd,$e,ab,Ua,Ka,Cb,oc,xc]),si=Is(),Vg=hy(M,{selector:bqb,equalityFn:pf})??[],Oe=uIb(),sf=(0,z.useRef)(null),
Ac=(0,z.useRef)([]);Ac.current=Ba;var cf=(0,z.useRef)(null);cf.current===null&&(cf.current=new Set);(0,z.useEffect)(()=>{cf.current?.forEach(xd=>{xd()})},[Ba,db]);(0,z.useImperativeHandle)(wa,()=>({lexicalRef:Pb,setMediaAttachments:Ja,getMediaAttachments:()=>Ac.current,floatingContentRef:sf,forgetTrackedUploads:Oa,subscribeMediaChange:xd=>{cf.current?.add(xd);return()=>cf.current?.delete(xd)}}),[Oa]);var sj=(0,z.useCallback)(async(xd,Cd)=>{var Qe=d,Re=d;try{if(!Ma||!M||Re(await Qe(Oe(M,xd,async(Dh,
fk)=>{var Zk=d,$k=d;try{try{return $k(await Zk(Ma({messageId:Dh,recipient:M}))),!0}catch(xn){return $k(),fk.dispose(),si("queued_message_edit_failed",xn),!1}}finally{Zk()}})))===!0){if(Pb.current)try{let Dh=FH(Cd.items);Pb.current.setEditorState(dD(Pb.current,Dh))}catch(Dh){si("queued_message_edit_failed",Dh)}Cd.media&&Ja(Cd.media);b&&M&&b({cascadeId:M,comments:Cd})}}finally{Qe()}},[Pb,Ma,M,si,b,Oe]),Ah=(0,z.useCallback)(async(xd,Cd)=>{var Qe=d,Re=d;try{Ma&&M&&Re(await Qe(Oe(M,xd,async(Dh,fk)=>{var Zk=
d,$k=d;try{try{$k(await Zk(a(Cd.items,Cd.media,()=>{},void 0,R.MessageDeliveryStrategy.NEXT_INVOCATION,{artifactComments:Cd.artifactComments,fileDiffComments:Cd.fileDiffComments,fileComments:Cd.fileComments})))}catch(xn){$k();fk.dispose();si("queued_message_send_failed",xn);return}try{$k(await Zk(Ma({messageId:Dh,recipient:M})))}catch(xn){$k(),si("queued_message_delete_failed",xn)}}finally{Zk()}})))}finally{Qe()}},[Ma,M,a,si,Oe]),ek=(0,z.useCallback)((xd,Cd)=>{var Qe=xd.getEditorState(),Re=AH(Qe),
Dh=Aa();a(Re,Dh,()=>{GH(xd);Oa();Ja([])},Cd);Q&&Q.addEntry(JSON.stringify(Qe.toJSON()));xa&&(xd._rootElement?.blur(),wn(!1))},[a,Aa,Oa,Q,xa]),Wg=oKa(Ba),Xg=(0,z.useMemo)(()=>tKa(Ba,y,Wg),[Ba,y,Wg]),[Ri,Id]=(0,z.useState)(!1);(0,z.useEffect)(()=>{Id(!!Xg);Xg&&dm(`Attachment error: ${Xg}`)},[Xg]);(0,z.useEffect)(()=>{pb&&dm(`Upload error: ${pb}`)},[pb]);(0,z.useEffect)(()=>{Va&&dm(`MCP error: ${Va}`)},[Va]);var Qc=va.get("instantPromptInput"),{userStatus:Bh}=Gx(),zg=Qc?!Bh?.cascadeModelConfigData:!1,
Df=(0,z.useRef)(!1),tb=(0,z.useCallback)(async(xd,Cd)=>{var Qe=d,Re=d;try{if(!Df.current){if(ed.isRecording||ed.isFinalizing){Df.current=!0;try{Re(await Qe(ed.stopAndFinalize()))}finally{Re(),Df.current=!1}}ek(xd,Cd)}}finally{Qe()}},[ed,ek]),wp=(0,z.useCallback)(async(xd,Cd)=>{var Qe=d,Re=d;try{if(!zg){if(xd.altKey&&M&&!ed.isRecording&&!ed.isFinalizing&&Ac.current.length===0&&DH(Cd.getEditorState())){let fk=tIb(Vg);if(fk.length>0){Ah(fk[0].msgId,fk[0].step);return}}var Dh=Cd._rootElement;Dh&&PR?.logEvent("keyboard_enter",
Dh);Re(await Qe(tb(Cd,xd)))}}finally{Qe()}},[zg,tb,M,ed.isRecording,ed.isFinalizing,Vg,Ah]),sn=(0,z.useCallback)(xd=>{Ja(Cd=>[...Cd,...xd])},[]),tn=YJ("max-media-attachments",5),{handleMediaPaste:un,handleMediaFiles:Ur}=f4a(sn,Ba.length,C,lb,tn),[$y,xp]=(0,z.useState)(!0),Vr=(0,z.useCallback)(xd=>{xp(DH(xd));ya&&xd.read(()=>{var Cd=mD().getTextContent();ya(Cd)})},[ya]),Pe=CIb(c),{isDraggingMedia:Qu}=V3a({onMediaDrop:Ur,allowVideo:C}),Ch=va.get("progressIndicator"),bg=!oa&&W!==void 0&&Z&&S?.mode!==
"standalone",Yk=w&&(bg||!!u),Wr=M&&Vg.length>0||!!t||!!pa||!!pb||Ri&&!!Xg||!!Va,az=(0,z.useRef)(null),yp=(0,z.useRef)(null),Xr=RR("AGENT_INPUT_BOX",["keyboard_enter"]),zp=(0,z.useCallback)(xd=>{az.current=xd;Xr(xd)},[Xr]),hm=!!xa,[Ru,vn]=(0,z.useState)(!1),wn=vn;(0,z.useEffect)(()=>{if(hm){var xd=yp.current;if(xd){var Cd=()=>wn(!0),Qe=Re=>{Re=Re.target;Re&&(xd.contains(Re)||Re.closest('.no-focus-agent-input,[role="menu"],[role="listbox"],[role="dialog"]'))||(wn(!1),Re=document.activeElement,Re instanceof
HTMLElement&&xd.contains(Re)&&Re.blur())};xd.addEventListener("focusin",Cd);document.addEventListener("pointerdown",Qe,!0);return()=>{xd.removeEventListener("focusin",Cd);document.removeEventListener("pointerdown",Qe,!0)}}}},[hm]);return z.createElement("div",{ref:yp,"data-testid":"agent-input-box",className:"flex flex-col w-full shrink-0",style:Ia?{paddingBottom:"max(0px, env(safe-area-inset-bottom))"}:void 0},z.createElement("div",{ref:sf,className:jj("flex flex-col gap-2 w-full",Wr?"mb-2":"h-0 overflow-hidden")},
M&&z.createElement(z2,{pendingAgentMessages:Vg,cascadeId:M,onEdit:sj,onSendNow:Ah}),t,pa,pb&&z.createElement(sIb,{errorMessage:pb,onDismiss:()=>lb(null)}),Ri&&Xg&&z.createElement(sIb,{errorMessage:Xg,onDismiss:()=>Id(!1)}),Va&&z.createElement(dIb,{title:"Error fetching MCP prompt",errorMessage:Va,onDismiss:()=>Ra(null)})),ja&&z.createElement("div",{className:jj("grid transition-[grid-template-rows,opacity] duration-300 ease-expo-out",!xa||Ru?"grid-rows-[1fr] opacity-100":"grid-rows-[0fr] opacity-0")},
z.createElement("div",{className:"overflow-hidden pb-2"},ja)),z.createElement("div",{ref:zp,id:"antigravity.agentSidePanelInputBox",className:"relative flex flex-col p-px rounded-2xl bg-card-border"},ua,z.createElement("div",{className:"relative flex flex-col gap-0 p-1 rounded-[calc(theme(borderRadius.2xl)-1px)] bg-card"},Ch&&z.createElement(gob,{isRunning:l}),z.createElement(iLa,{isDraggingImage:Ca?Qu:!1}),z.createElement("div",{className:"relative w-full"},(ed.isRecording&&!Cf||Ba.length>0||!!g)&&
z.createElement("div",{className:"flex items-center flex-wrap gap-1 border-b border-border p-1 animate-in fade-in duration-10"},Ba.length>0&&z.createElement(cIb,{selectedMedia:Ba,setSelectedMedia:Ja}),g,ed.isRecording&&!Cf&&z.createElement(iob,{isRecording:ed.isRecording,stopRecording:ed.stopRecording,cancelRecording:ed.cancelRecording,error:ed.error})),z.createElement("div",{className:"w-full rounded-lg transition-all duration-10"},z.createElement(rI,{placeholder:La,handleEnter:wp,initialContent:k,
handleKeyDown:Pe,forcePlainTextPaste:!0,onEditorChange:Vr,lexicalRef:Pb,handleMediaPaste:un,contentEditableClassName:jj("text-sm [@media(pointer:coarse)]:text-base",e),mentionsConfig:f,resolveWorkspaceUrlPreview:D,onDriveLinkResolveError:F,getSlashCommandItems:G,getMcpPrompt:J,onMcpPromptFetchingChange:Gb,onMcpPromptError:Ra,contextMenuPopupFn:K,messageHistoryConfig:Q,disabled:ca,disableAutoFocus:la,portalAnchorRef:az,prefetchSlashCommands:fa,spellCheck:Fa,autoCorrect:Fa,cascadeId:M}))),z.createElement(rIb,
{cancelInvocation:c,isRunning:l,isConvoInputEmpty:$y,hasPendingComments:m,isConvoLoading:n,handleSubmit:tb,modelSelector:p,optOutButton:q,currentModelConfig:y,handleImageUpload:Ur,lexicalRef:Pb,dropdownPlacement:B,attachmentsError:Xg,captureScreenRecording:E,...ed,hasAttachments:Ba.length>0,isStreamingTranscriptionEnabled:Cf,isUploading:db,isFetchingMcpPrompts:Xa,agentScripts:L,inExistingConversation:P,conversationAgentScript:N,hasQuotaOrCredits:O,selectedEnvironment:W,battleMode:da,autonomousModeConfig:qa,
setSelectedEnvironment:w?void 0:Z,environmentSelectorCompact:aa,isCreatingEnvironment:ca,isGitRepo:ba,isCitcWorkspace:ha,isPendingNewWorkspace:na,isSignedIn:ea,getSlashCommandItems:G,sideQuestionControl:A})),Yk&&z.createElement($U,{shouldShow:!xa||Ru,easingClassName:"ease-expo-out"},z.createElement("div",{className:"flex w-full items-center justify-between py-1 px-2.5 gap-2 text-xs"},bg&&z.createElement(AIb,{resourceManagementProps:S,dropdownPlacement:B,inExistingConversation:P,selectedEnvironment:W,
setSelectedEnvironment:Z,environmentSelectorCompact:aa,isCreatingEnvironment:ca,isGitRepo:ba,isCitcWorkspace:ha,isPendingNewWorkspace:na,isPseudoProjectSelected:oa}),(v||u)&&z.createElement("div",{className:"shrink-0 whitespace-nowrap ml-auto flex items-center gap-0.5"},v,u)))))});A2.displayName="AgentInputBox";function 