#!/system/bin/sh
SCRIPT="$0"
case "$SCRIPT" in
  /*) DIR="${SCRIPT%/*}" ;;
  */*) DIR="$(pwd)/${SCRIPT%/*}" ;;
  *) DIR="$(pwd)" ;;
esac
export SSL_CERT_FILE="$DIR/../../etc/ssl/certs/ca-certificates.crt"
export CURL_CA_BUNDLE="$DIR/../../etc/ssl/certs/ca-certificates.crt"
export LD_LIBRARY_PATH="$DIR/..:/system/lib64:$LD_LIBRARY_PATH"
exec "$DIR/../ld-linux-aarch64.so.1" --library-path "$DIR/..:/system/lib64" "$DIR/git-remote-http.bin" "$@"
